### PR TITLE
Change scatter to scatter_mark

### PR DESCRIPTION
**Pull request by patudom**

### CODE REVIEW

**Comment by Carifio24** [comment]
In addition to changing the `scatter` -> `scatter_mark` references, I've also reconfigured the spectrum viewer. With https://github.com/glue-viz/glue-jupyter/pull/398, we no longer need our own layer artist for the spectrum viewer (and the fact that we were replacing the scatter mark with a line one actually causes problems with some glue-jupyter updates). I also did a bit of code cleanup.

**Comment by patudom** [comment]
At Stage 4, marker `bes_fit1`, the best fit line button triggers an error.
Screen Shot 2023-10-23 at 5 52 13 PM

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:764, in Widget._handle_msg(self, msg)
    762         if 'buffer_paths' in data:
    763             _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 764         self.set_state(state)
    766 # Handle a state request.
    767 elif method == 'request_state':

File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:633, in Widget.set_state(self, sync_data)
    630 if name in self.keys:
    631     from_json = self.trait_metadata(name, 'from_json',
    632                                     self._trait_from_json)
--> 633     self.set_trait(name, from_json(sync_data[name], self))

File ~/opt/anaconda3/envs/newbase/lib/python3.8/contextlib.py:120, in _GeneratorContextManager.__exit__(self, type, value, traceback)
    118 if type is None:
    119     try:
--> 120         next(self.gen)
    121     except StopIteration:
    122         return False

File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/traitlets/traitlets.py:1502, in HasTraits.hold_trait_notifications(self)
   1500 for changes in cache.values():
   1501     for change in changes:
-> 1502         self.notify_change(change)

File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:694, in Widget.notify_change(self, change)
    691     if name in self.keys and self._should_send_property(name, getattr(self, name)):
    692         # Send new state to front-end
    693         self.send_state(key=name)
--> 694 super(Widget, self).notify_change(change)

File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/traitlets/traitlets.py:1517, in HasTraits.notify_change(self, change)
   1515 def notify_change(self, change):
   1516     """Notify observers of a change event"""
-> 1517     return self._notify_observers(change)

File ~/opt/anaconda3/envs/newbase/lib/python3.8/site-packages/traitlets/traitlets.py:1564, in HasTraits._notify_observers(self, event)
   1561 elif isinstance(c, EventHandler) and c.name is not None:
   1562     c = getattr(self, c.name)
-> 1564 c(event)

File ~/Documents/GitHub/cosmicds/cosmicds/components/toolbar/toolbar.py:45, in Toolbar._on_change_v_model(self, change)
     41         self.active_tool = self.tools[change.new]
     42     else:
     43         # In this case it is a non-checkable tool and we should
     44         # activate it but not keep the tool checked in the toolbar
---> 45         self.tools[change.new].activate()
     46         self.active_tool_id = None
     47 else:

File ~/Documents/GitHub/hubbleds/src/hubbleds/tools/hubble_line_fit_tool.py:21, in HubbleLineFitTool.activate(self)
     20 def activate(self):
---> 21     super().activate()

File ~/Documents/GitHub/cosmicds/cosmicds/tools/line_fit_tool.py:55, in LineFitTool.activate(self)
     53 def activate(self):
     54     if not self.active:
---> 55         self._fit_to_layers()
     56         self.tool_tip = self.active_tool_tip
     57     else:

File ~/Documents/GitHub/cosmicds/cosmicds/tools/line_fit_tool.py:254, in LineFitTool._fit_to_layers(self)
    252 for layer in self.visible_layers:
    253     if not any(condition(layer) for condition in self._ignore_conditions):
--> 254         self._fit_to_layer(layer, add_marks=False)
    256 self.figure.marks = self.figure.marks + list(self.line_marks)

File ~/Documents/GitHub/cosmicds/cosmicds/tools/line_fit_tool.py:237, in LineFitTool._fit_to_layer(self, layer, add_marks)
    235 def _fit_to_layer(self, layer, add_marks=True):
    236     try:
--> 237         line, slope = self._create_fit_line(layer)
    238         if line is None:
    239             return

File ~/Documents/GitHub/cosmicds/cosmicds/tools/line_fit_tool.py:212, in LineFitTool._create_fit_line(self, layer)
    210 label = self.label(layer, fit) if self.show_labels else None
    211 color = layer.state.color if layer.state.color != '0.35' else 'black'
--> 212 line = line_mark(layer, start_x, start_y, end_x, end_y, color, label)
    213 return line, slope

File ~/Documents/GitHub/cosmicds/cosmicds/utils.py:247, in line_mark(layer, start_x, start_y, end_x, end_y, color, label, label_visibility)
    228 """
    229 Creates a Lines mark between the given start and end points
    230 using the scales of the given layer.
   (...)
    244     The desired color of the line, represented as a hex string.
    245 """
    246 if isinstance(layer, BqplotScatterLayerArtist):
--> 247     scales = layer.image.scales
    248 elif isinstance(layer, BqplotHistogramLayerArtist):
    249     scales = layer.view.scales

AttributeError: 'BqplotScatterLayerArtist' object has no attribute 'image'
```

**Comment by patudom** [comment]
Note to self - I got as far as Stage 5 ran_var 1, but I can't advance past that point because of the best fit line issue.

**Comment by Carifio24** [comment]
The most recent commit on https://github.com/cosmicds/cosmicds/pull/267 should fix the best fit line tool. I've also updated the sizes to account for the glue-jupyter update - obviously feel free to make more adjustments.

**Pull request merged**
