### PR TITLE
Finish new stage 1 tutorial front end

### PR DESCRIPTION
**Pull request by patudom**
This is the latest on the Stage 1 velocity measurement tutorial, which builds off #186, which I think we can close. There are some issues still, some of which I try to fix here. I will note in comments other issues that still linger.

(I cut out chunks of the tutorial code that are related to the subset towers since we don't use them here. I think the errors I see here were in #186 too, but it would be good to verify that I didn't break anything with my updates.

New in this PR:

- Guidelines text is shortened where possible
- Update stage_1.vue layout a bit
- Slightly resequence when state variables are triggered
- Remove unused c-spectrum-measurement-tutorial from stage_1.vue (I tried to remove it all together from the code, but that broke a lot of stuff)
- Remove unused code related to tower subsets
- Apply light/dark mode styling to dotplot_viewer_3 in the slideshow

### CODE REVIEW

**Comment by patudom** [comment]
Cosmetic:

In dot plot tutorial slideshow, the dot markers randomly change size between slides
Screen Shot 2023-04-29 at 8 15 42 PM

Screen Shot 2023-04-29 at 8 14 32 PM

**Comment by patudom** [comment]
Should be fixed:

If the zoom tool is used in the dot plot slideshow, it triggers these errors:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/opt/anaconda3/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/opt/anaconda3/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    118         if type is None:
    119             try:
--> 120                 next(self.gen)
    121             except StopIteration:
    122                 return False

~/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1214                 for changes in cache.values():
   1215                     for change in changes:
-> 1216                         self.notify_change(change)
   1217 
   1218     def _notify_trait(self, name, old_value, new_value):

~/opt/anaconda3/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

~/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1227     def notify_change(self, change):
   1228         """Notify observers of a change event"""
-> 1229         return self._notify_observers(change)
   1230 
   1231     def _notify_observers(self, event):

~/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1264                 c = getattr(self, c.name)
   1265 
-> 1266             c(event)
   1267 
   1268     def _add_notifiers(self, handler, name, type):

~/opt/anaconda3/lib/python3.8/site-packages/cosmicds/tools/zoom_tools.py in update_selection(self, *args)
     30 
     31         self._reset_interact()
---> 32         self.activate()
     33 
     34     def deactivate(self):

~/opt/anaconda3/lib/python3.8/site-packages/cosmicds/utils.py in extended_activate()
    186     def extended_activate():
    187         if activate_before_tool:
--> 188             activate_cb()
    189         activate()
    190         if not activate_before_tool:

~/Documents/GitHub/hubbleds/src/hubbleds/components/dotplot_tutorial_slideshow/dotplot_tutorial_slideshow.py in on_zoom_active(self, *args, **kwargs)
     72 
     73     def on_zoom_active(self, *args, **kwargs):
---> 74         self.vue_removeMeasuringTool()
     75 
     76     def on_zoom_deactive(self, *args, **kwargs):

~/Documents/GitHub/hubbleds/src/hubbleds/components/dotplot_tutorial_slideshow/dotplot_tutorial_slideshow.py in vue_removeMeasuringTool(self, _data)
     66 
     67     def vue_removeMeasuringTool(self, _data = None):
---> 68         self.dotplot_viewer_viewer.remove_event_callback( self.dotplot_viewer_viewer._on_click)
     69         self.dotplot_viewer_viewer.show_previous_line(False, False)
     70         self.dotplot_viewer_viewer.show_line(False, False)

~/opt/anaconda3/lib/python3.8/site-packages/glue_jupyter/bqplot/common/viewer.py in remove_event_callback(self, callback)
    167         """
    168         key = self._callback_key(callback)
--> 169         self._events_for_callback.pop(key)
    170         self._event_callbacks.remove(callback)
    171         self._update_interact_events()

KeyError: (<function LineHoverViewerMixin._on_click at 0x7f98fb626040>, (<cosmicds.viewers.cds_viewer.viewer.HubbleDotPlotView object at 0x7f9918cce460>,))
```

**Comment by patudom** [comment]
needs fixing:

See note on guideline dot_seq5. The measuring tool in the dot plot works, but nothing happens in the spectrum viewer. We don't need to hook up the click to mark functionality. We can just have the vertical markers in the 2 viewers move in tandem.

**Comment by patudom** [comment]
needs fixing:

at marker dot_seq13, the spectrum viewer measuring tool needs to be activated. 

Also, the "first" marker should be taken off.

**Comment by johnarban** [comment]
I can look at this and fix up these issues

**Comment by patudom** [comment]
Needs fixing:

This one is probably because of something I did because I don't recall it behaving this way in #186.

On the last guideline of the dot_seq (now dot_seq14), you can't advance. 

These errors are triggered:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/opt/anaconda3/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/opt/anaconda3/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_json(self, json, widget)
    175         self._block_on_state_change = True
    176         try:
--> 177             update_state_from_dict(state, json)
    178         finally:
    179             self._block_on_state_change = False

~/opt/anaconda3/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_dict(state, changes)
     76                         setattr(state, name, get_cmap(changes[name]))
     77                     else:
---> 78                         setattr(state, name, changes[name])
     79 
     80 

~/opt/anaconda3/lib/python3.8/site-packages/echo/core.py in __setattr__(self, attribute, value)
    259 
    260     def __setattr__(self, attribute, value):
--> 261         super(HasCallbackProperties, self).__setattr__(attribute, value)
    262         if self.is_callback_property(attribute):
    263             self._notify_global(**{attribute: value})

~/opt/anaconda3/lib/python3.8/site-packages/echo/core.py in __set__(self, instance, value)
     71         except AttributeError:  # pragma: no cover
     72             old = None
---> 73         self._setter(instance, value)
     74         new = self.__get__(instance)
     75         if old != new:

~/Documents/GitHub/hubbleds/src/hubbleds/stages/stage_1.py in marker_forward(self, value)
    242         index = self.indices[self.marker]
    243         new_index = min(max(index + value, 0), len(self.markers) - 1)
--> 244         self.marker = self.markers[new_index]
    245 
    246     def marker_before(self, marker):

~/opt/anaconda3/lib/python3.8/site-packages/echo/core.py in __setattr__(self, attribute, value)
    259 
    260     def __setattr__(self, attribute, value):
--> 261         super(HasCallbackProperties, self).__setattr__(attribute, value)
    262         if self.is_callback_property(attribute):
    263             self._notify_global(**{attribute: value})

~/opt/anaconda3/lib/python3.8/site-packages/echo/core.py in __set__(self, instance, value)
     74         new = self.__get__(instance)
     75         if old != new:
---> 76             self.notify(instance, old, new)
     77 
     78     def setter(self, func):

~/opt/anaconda3/lib/python3.8/site-packages/echo/core.py in notify(self, instance, old, new)
    125             cback(new)
    126         for cback in self._2arg_callbacks.get(instance, []):
--> 127             cback(old, new)
    128 
    129     def disable(self, instance):

~/Documents/GitHub/hubbleds/src/hubbleds/stages/stage_1.py in _on_marker_update(self, old, new)
    666 
    667         if advancing and new == "rem_gal1":
--> 668             self.spectrum_measurement_tutorial.vue_on_close()
    669 
    670     def _on_step_index_update(self, index):

~/Documents/GitHub/hubbleds/src/hubbleds/components/spectrum_measurement_tutorial_sequence/spectrum_measurement_tutorial.py in vue_on_close(self, data)
    689         self.spectrum_viewer.line.visible = True
    690         self.spectrum_viewer.line_label.visible = True
--> 691         self.unobserve(self._on_data_change, ['show_first_measurment', 'show_second_measurment'])
    692         self.unobserve(self.toggle_specview_mouse_interaction, 'allow_specview_mouse_interaction')
    693         self.unobserve(self.vue_enable_zoom_tool, 'zoom_tool_enabled')

~/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py in unobserve(self, handler, names, type)
   1374         names = parse_notifier_name(names)
   1375         for n in names:
-> 1376             self._remove_notifiers(handler, n, type)
   1377 
   1378     def unobserve_all(self, name=All):

~/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py in _remove_notifiers(self, handler, name, type)
   1284                 del self._trait_notifiers[name][type]
   1285             else:
-> 1286                 self._trait_notifiers[name][type].remove(handler)
   1287         except KeyError:
   1288             pass

ValueError: list.remove(x): x not in list
```

**Comment by johnarban** [comment]
Everything with 👍🏾 should be fixed

and yes, #186 can be closed w/o merging

**Comment by patudom** [comment]
Thanks so much, @johnarban!! This is in pretty good shape now. There are a couple interactions that are still not working for me, but nothing gets "stuck," so I am going to merge this in and note down the lingering issues in my next PR (where I will also tidy up a bit more in the front end). Thanks again!!🌟

**Pull request merged**
