### PR TITLE
Wire up stage 4 slideshow mc question

### PR DESCRIPTION
**Pull request by patudom**
This adds the mc question to the Stage 4 slideshow & sets up the the event handlers to store slideshow progress in the state.

### CODE REVIEW

**Comment by patudom** [comment]
@Carifio24, on a reload, this stage now gives these errors. I'm wondering if this is related to the viewers we are passing to the slideshow? (This doesn't look like anything that would be related to the mc question or other slideshow content).
```
Traceback (most recent call last):
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1707, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/04-explore-data/__init__.py", line 68, in Page
    solara.lab.use_task(_load_class_data)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 846, in use_task
    return wrapper(f)
           ^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 840, in wrapper
    raise task_instance.exception
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/tasks.py", line 259, in runner
    self._last_value = value = await self.function(*args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/04-explore-data/__init__.py", line 66, in _load_class_data
    class_data_loaded.set(True)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 358, in set
    self._storage.set(value)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 266, in set
    self.fire(value, old)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/solara/toestand.py", line 152, in fire
    listener(new)
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/pages/04-explore-data/__init__.py", line 117, in _on_class_data_loaded
    class_data = GLOBAL_STATE.value.add_or_update_data(class_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/cosmicds/src/cosmicds/state.py", line 66, in add_or_update_data
    existing.update_values_from_data(data)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/data.py", line 1593, in update_values_from_data
    self.remove_component(cid)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/data.py", line 859, in remove_component
    self.hub.broadcast(msg)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/hub.py", line 215, in broadcast
    handler(message)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/data_combo_helper.py", line 379, in refresh
    self.choices = choices
    ^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/data_combo_helper.py", line 84, in choices
    with delay_callback(self.state, self.selection_property):
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/echo/core.py", line 538, in __exit__
    p.notify(*args)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/utils/matplotlib.py", line 170, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/viewers/matplotlib/state.py", line 38, in notify
    super(DeferredDrawSelectionCallbackProperty, self).notify(*args, **kwargs)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/echo/core.py", line 125, in notify
    cback(new)
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/viewers/scatter/state.py", line 360, in _check_for_preferred_cmap
    actual_component = layer.get_component(self.cmap_att)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/glue/core/data.py", line 1462, in get_component
    raise IncompatibleAttribute()
glue.core.exceptions.IncompatibleAttribute
```

**Comment by patudom** [comment]
@Carifio24, when your slideshow reloads, is there data in the class viewer? Mine doesn't have any data.
Screenshot 2024-07-22 at 3 34 25 PM

**Comment by Carifio24** [comment]
@patudom My most recent commit fixes the reloading issue for me.

**Comment by patudom** [comment]
Works for me too - thanks, @Carifio24! Does the rest of this PR otherwise look ok to you?

**Comment by Carifio24** [comment]
@patudom I don't see any other issues

**Pull request merged**
