### PR TITLE
UX updates to intro slideshow

### PR DESCRIPTION
**Pull request by johnarban**
The PR makes several minor changes to the UX

 - Disables the non-spiral buttons in the intro on the Shapley page
 - Initializes the 3rd exploration tool to show a galaxy
 - make sure team only components are hidden when `show_team_interface=False` (only affects the select 5 galaxies button)

### CODE REVIEW

**Comment by patudom** [comment]
@johnarban, let me know if this is intentionally marked as a draft. It looks good to me, and I will merge it if you aren't still working on it. Thanks!

**Comment by johnarban** [comment]
Hi @patudom, yeah this is good to merge. I was gonna try to include the button highlight, but that's taking too long

**Comment by patudom** [comment]
If I press a button on Slide 4, it remains pressed on Slide 5. Would it be possible to unselect all the buttons when leaving Slide 4 and start Slide 5 with the M31 button pressed? Thank you! This looks great - just like @aagoodman has been requesting for probably a year now. :) 
Screen Shot 2022-10-11 at 6 47 14 PM

**Comment by johnarban** [comment]
@patudom I've fixed the issue with the selection persisting, and also added another [commit](https://github.com/cosmicds/hubbleds/pull/24/commits/b197eb5c87f8dd834ce72fee8a122747c084bf53) that makes sure resetting the cosmic sky viewer clears the table selection

**Review by patudom — APPROVED** [review]

**Pull request merged**
