### PR TITLE
Add class info to all data

### PR DESCRIPTION
**Pull request by Carifio24**
This PR adds the student's class info to the "all data" datasets:
* Calculate the age value from the class's measurements and add it to the "all class summaries" dataset
* Add all of the individual measurements from the class to the "all measurements" dataset

This builds off of #687 and addresses a couple of the points in #660.

### CODE REVIEW

**Comment by patudom** [comment]
@Carifio24, when I run this PR, "my class's" data set appears blank in the slider viewer. Does it show up for you? (Stage 5, marker 'cla_res1c1`).

https://github.com/user-attachments/assets/1e10f3b7-3706-48b3-b2ad-553f0a966f6e

**Comment by Carifio24** [comment]
Which class ID is this for?

**Comment by patudom** [comment]
215 (the class that has the demo2024 code).

**Comment by Carifio24** [comment]
@patudom Does my most recent commit fix the issue for you?

**Comment by patudom** [comment]
Yes, thank you, Jon!

**Pull request merged**
