### PR TITLE
Cherry pick to demo 2

### PR DESCRIPTION
**Pull request by patudom**
This cherry picks commits from more recent PRs to the demo branch.

### CODE REVIEW

**Comment by patudom** [comment]
The commits to prevent skipping ahead using the left navigation menu weren't working on this branch - is that because this branch does not read from or write to the db? And is it ok to allow skipping ahead? (If you try to jump to Stage 5 without having measurements, the app will crash).

**Comment by johnarban** [comment]
@patudom This does not seem to have any commits from #670. Was this just in local testing? Preventing skipping should work without updating the db, as the necessary info is stored in the state. 

So far as stage 5 failing, we should just find some way to get around the issue, can you copy the error here?

**Comment by patudom** [comment]
> @patudom This does not seem to have any commits from #670. Was this just in local testing? Preventing skipping should work without updating the db, as the necessary info is stored in the state.

Yeah, I cherry picked them locally and they did not prevent moving forward.

**Review by johnarban — COMMENTED** [review]
> > @patudom This does not seem to have any commits from #670. Was this just in local testing? Preventing skipping should work without updating the db, as the necessary info is stored in the state.
> 
> Yeah, I cherry picked them locally and they did not prevent moving forward. 

Alright, so the issues is actually in `cosmicds`. By default the `max_route_index` is None, which disables the effect. This should be defaulted to zero.

**Comment by patudom** [comment]
This is working - thank you!

**Pull request merged**
