### PR TITLE
Set up dot plot viewer to display 2nd seed measurements

### LINKED ISSUE #655: Set up dot plot viewer to display 2nd seed measurements

### PR DESCRIPTION
**Pull request by johnarban**
This PR fixes #655 showing the second set of dotplot data. This enables this through several changes. 
- updates `create_dotplot_viewer` updates the arguments to be more declarative so that it is easier to customize each dotplot, allowing the user to set whether it shows the first, second, or full data sets for the example and seed measurements
- The example seed measurements are placed into 3 different glue data objects. This is needed to circumvent the dotplot's native method of handling the y-axis height when displaying a subset. We want the bounds to be set by the smaller data set (the first or second measurements) rather than the full dataset. If we use subsets, then the y-axis bounds are set by the larger (full) dataset, rather than just by what is visible.

This also fixes the spectrum wavelength label

### CODE REVIEW

**Comment by Carifio24** [comment]
This should now fix #652.

**Comment by patudom** [comment]
Per our conversation yesterday, the 2nd measurement is not showing up for me either, so I think we need to track down what's going on. It's really weird that there are things that work for @Carifio24 that don't work for me and @johnarban.

**Comment by Carifio24** [comment]
Yeah, it's very strange that this works for me and not for both of you. For the purposes of comparison, my versions of our most relevant packages are:
```
glue-core==1.21.0
glue-jupyter==0.20.1
glue-plotly==0.10.0
pydantic==2.6.4
pydantic_core==2.16.3
solara==1.40.0
solara-enterprise==1.40.0
solara-server==1.40.0
solara-ui==1.40.0
```

**Comment by patudom** [comment]
Mine are a bit different. Does this mean I set up my common solara environment incorrectly? 🤦‍♀️

These are the ones that are different. Should I try reverting to your versions and see if it works?  (It seems troubling to me that mine are newer and my version is one of the ones that isn't working..)

```
glue-jupyter==0.21.0  
pydantic==2.7.3
pydantic-core==2.18.4
```

**Comment by patudom** [comment]
Just tried reverting to your packages and the 2nd measurement is still not appearing.

**Comment by Carifio24** [comment]
So I was playing around with this some more, went back and re-did my student's first measurement, and then went forward again, and now the second measurement isn't updating with the line.

**Comment by Carifio24** [comment]
Okay, after a long dive through the inner workings of the glue parts of all this, I think I finally figured out what the issue is. @patudom and @johnarban whenever you get a chance, let me know whether this works for you.

**Comment by patudom** [comment]
It's working!! I will go ahead and merge. Thanks for tracking this down, @Carifio24!

**Pull request merged**
