### PR TITLE
Prevent skipping stages

### LINKED ISSUE #577: Don't allow users to skip ahead in stages using left navigation menu

### PR DESCRIPTION
**Pull request by johnarban**
This PR fixes #577 in combination with https://github.com/cosmicds/cosmicds/pull/347. It stores the max stage index in the local state. This PR builds on top of #626

### CODE REVIEW

**Comment by patudom** [comment]
The functionality to prevent skipping stages seems to be working well, but sometimes the stage that's being highlighted (which we still need to style to a better contrast) is not the stage that I'm on. Here, I advanced from the intro stage to Stage 1, but Stage 2 is highlighted in the left menu. (If I refresh the page, it correctly highlights Stage 1).

Screenshot 2024-10-21 at 11 03 04 AM

**Comment by johnarban** [comment]
@patudom  --- this issue I think is fixed with this commit https://github.com/cosmicds/cosmicds/pull/347/commits/16b53ad83203e43d8562cef1c7917750073a8d75 to https://github.com/cosmicds/cosmicds/pull/347

**Comment by patudom** [comment]
With the new commit in https://github.com/cosmicds/cosmicds/pull/347, when I run the app with a fresh student, I immediately get this error:
```
Traceback (most recent call last):
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/reacton/core.py", line 1707, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/Documents/GitHub/hubbleds/src/hubbleds/layout.py", line 27, in Layout
    Ref(LOCAL_STATE.fields.max_route_index).set(max(route_index or 0, LOCAL_STATE.value.max_route_index or 0))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Pat/anaconda3/envs/common-solara/lib/python3.11/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'LocalState' object has no attribute 'max_route_index'
```

**Comment by patudom** [comment]
My bad - this was the same issue as I was having with a different cosmicds branch - my pip install wasn't behaving like it was in editable mode, so the updates from the branch were not registering. This is working well now - thank you!

**Pull request merged**
