### PR TITLE
add demo label in css; don't retrieve db data

### LINKED ISSUE #659: Demo branch updates
- [x] Add clear labeling in layout when user is on the demo branch version of story (Pat)
- [x] Don't read in student's story or stage states or any measurements when in demo mode. (John)
- [ ] Reset server to make sure updates deploy (Jon)

### PR DESCRIPTION
**Pull request by johnarban**
Addresses first 2 items in #659  Adds a simple demo label using `::after` CSS psuedo-class, along with a companion cosmicds PR https://github.com/cosmicds/cosmicds/pull/345

image

### CODE REVIEW

**Comment by patudom** [comment]
The demo text was breaking awkwardly on smaller screens.
Screenshot 2024-10-18 at 12 16 41 PM

I updated as such. It's a bit cramped for 2 lines, but I think it's better than the awkward break. Ok?
Screenshot 2024-10-18 at 12 18 20 PM

(This needs a small update I pushed to https://github.com/cosmicds/cosmicds/pull/345).

**Comment by patudom** [comment]
(The title bar defaults to 64px in height, but when I tried to use flex to make it expand beyond that, other bad things happened to the layout. If you know how to fix that, @johnarban, please feel free to make the text larger).

**Comment by johnarban** [comment]
Your changes look fine to me. I added a commit to decrease the line-height. I think the strong red draws enough attention that we don't need to make the font too large.

**Comment by Carifio24** [comment]
Looks good to me. My only comment is that some of the logger messages in the state (like e.g. https://github.com/cosmicds/hubbleds/blob/main/src/hubbleds/pages/01-spectra-%26-velocity/__init__.py#L98) are a bit confusing - the DB writing is correctly skipped and the logger message inside the API handler logs this, but you then see a "Wrote to the database" message.

This is minor, though. The functionality looks good to me!

**Pull request merged**
